name: Test Suite

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rubengmurray/npm-test-action/.github/workflows/test.yml@feat/callable-workflow